name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact

    - name: Deploy Binary
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: pointing-poker
        target: /root/

    - name: Deploy Service File
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: deployments/pointing-poker.service
        target: /etc/systemd/system/

    - name: Restart pointing-poker Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: systemctl restart pointing-poker